web:
  build: .
  dockerfile: ./Dockerfile.base
  volumes:
    - ..:/go/src/github.com/kdavh/gin-sms-vote
  ports:
    - "8080:8080"
  environment:
    DB_HOST: web_db
    DB_USER: postgres
    DB_PASSWORD: ${SMS_VOTE_POSTGRES_PASSWORD}
    # DB_NAME: ...db name here
    # GIN_MODE: ...
    PORT: "8080"
  working_dir: /go/src/github.com/kdavh/gin-sms-vote
  # command: ...

web_db:
  image: postgres:9.1
  volumes:
    - sms_vote_db_data:/var/lib/postgresql/
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ${SMS_VOTE_POSTGRES_PASSWORD}
    # POSTGRES_DB: ...db name here
